//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_cv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities : DbContext
    {
        public DbCVEntities()
            : base("name=DbCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Admin> Table_Admin { get; set; }
        public virtual DbSet<Table_Contact> Table_Contact { get; set; }
        public virtual DbSet<Table_educations> Table_educations { get; set; }
        public virtual DbSet<Table_Experiences> Table_Experiences { get; set; }
        public virtual DbSet<Table_Hobbies> Table_Hobbies { get; set; }
        public virtual DbSet<Table_skills> Table_skills { get; set; }
        public virtual DbSet<Table_about_me> Table_about_me { get; set; }
        public virtual DbSet<Table_Social_media> Table_Social_media { get; set; }
    }
}
